name: smart_device_mobile_app
description: "Smart device project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  top_snackbar_flutter: ^3.2.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.4
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  auto_route: ^9.3.0+1
  json_annotation: ^4.9.0
  auto_route_generator: ^9.3.1
  flutter_svg: ^2.0.17
  dropdown_button2: ^2.3.9
  copy_with_extension_gen: ^6.0.1
  get_it: ^8.0.3
  intl: ^0.20.2
  syncfusion_flutter_gauges: ^28.2.5
  dashed_circular_progress_bar: ^0.0.6
  simple_circular_progress_bar: ^1.0.2
  shared_preferences: ^2.5.2
  loading_indicator: ^3.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff" # (Android için arka plan rengi)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3



flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 100
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 200
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 300
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 500
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 600
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 700
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 800
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 900
